import React, { useState, useEffect } from 'react';
import { useFarm } from '../context/FarmContext';
import { advisoryApi } from '../services/advisoryApi';
import { FarmAdvisory } from '../services/types';
import { useLanguage } from '../context/LanguageContext';
import { Skeleton } from '../components/ui/Skeleton';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Clock, RefreshCw, ShieldCheck } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { API_BASE_URL } from '../lib/api/client';

export const AdvisoryHistoryPage: React.FC = () => {
  const { currentFarm, refreshAdvisory, currentAdvisory, isLoadingAdvisory } = useFarm();
  const { t } = useLanguage();
  const farmId = currentFarm ? ((currentFarm as any).id || (currentFarm as any)._id) : null;

  const [history, setHistory] = useState<FarmAdvisory[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  useEffect(() => {
    if (!farmId) { setIsLoading(false); return; }
    // Load advisory history from backend
    fetch(`${API_BASE_URL}/farms/${farmId}/advisories`, {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('sujalam_auth_token')}`,
      },
    })
      .then(r => r.json())
      .then(d => {
        if (d.success) setHistory(d.data || []);
      })
      .catch(() => {})
      .finally(() => setIsLoading(false));
  }, [farmId]);

  const handleRefreshAdvisory = async () => {
    setIsRefreshing(true);
    try {
      await refreshAdvisory();
      // Reload history
      if (farmId) {
        const r = await fetch(`${API_BASE_URL}/farms/${farmId}/advisories`, {
          headers: { Authorization: `Bearer ${localStorage.getItem('sujalam_auth_token')}` },
        });
        const d = await r.json();
        if (d.success) setHistory(d.data || []);
      }
    } finally {
      setIsRefreshing(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-charcoal-950">Advisory History</h2>
          <p className="text-xs sm:text-sm text-charcoal-600 mt-1">
            Past farm plans generated by the Sujalam Decision Engine.
          </p>
        </div>
        <Button
          variant="primary"
          size="sm"
          onClick={handleRefreshAdvisory}
          isLoading={isRefreshing || isLoadingAdvisory}
          leftIcon={<RefreshCw className="w-4 h-4" />}
          disabled={!farmId}
        >
          Refresh Plan
        </Button>
      </div>

      {/* Current advisory snapshot */}
      {currentAdvisory && (
        <Card variant="default" padding="lg">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-forest-800" />
              <h3 className="text-sm font-bold text-charcoal-900">Current Advisory</h3>
            </div>
            <Badge variant="forest" size="sm">Active</Badge>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Irrigation', value: currentAdvisory.irrigation.decision },
              { label: 'Crop Health', value: currentAdvisory.crop_health.decision },
              { label: 'Market', value: currentAdvisory.market.decision },
              { label: 'Weather Risk', value: currentAdvisory.weather.risk },
            ].map(({ label, value }) => (
              <div key={label} className="bg-ivory-100 rounded-xl p-3 text-center">
                <p className="text-[10px] font-bold text-charcoal-500 uppercase tracking-wider mb-1">{label}</p>
                <p className="text-sm font-extrabold text-forest-900">{value}</p>
              </div>
            ))}
          </div>
          <p className="text-[11px] text-charcoal-500 mt-3 flex items-center gap-1">
            <Clock className="w-3 h-3" />
            Generated: {new Date(currentAdvisory.generated_at).toLocaleString()}
          </p>
        </Card>
      )}

      {/* History list */}
      {isLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-32 w-full rounded-2xl" />
          <Skeleton className="h-32 w-full rounded-2xl" />
        </div>
      ) : history.length === 0 ? (
        <div className="flex flex-col items-center justify-center p-8 bg-white rounded-3xl border border-ivory-300 shadow-sm text-center">
          <Clock className="w-16 h-16 text-forest-300 mb-4" />
          <h2 className="text-xl font-bold text-charcoal-900 mb-2">No Advisory History Yet</h2>
          <p className="text-sm text-charcoal-600 mb-6 max-w-md">
            Your generated farm plans will appear here. Refresh your advisory to create one.
          </p>
          <Button
            onClick={handleRefreshAdvisory}
            isLoading={isRefreshing}
            leftIcon={<RefreshCw className="w-4 h-4" />}
          >
            Generate First Advisory
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          {history.map((adv, i) => (
            <Card key={(adv as any).id || i} variant="default" padding="md">
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs font-bold text-charcoal-500 flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {new Date(adv.generated_at).toLocaleString()}
                </p>
                <Badge variant="info" size="sm">{(adv as any).supporting_signals?.confidence_percent ?? '—'}% Conf.</Badge>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                {[
                  { label: 'Irrigation', value: adv.irrigation?.decision },
                  { label: 'Crop', value: adv.crop_health?.decision },
                  { label: 'Market', value: adv.market?.decision },
                  { label: 'Weather', value: adv.weather?.risk },
                ].map(({ label, value }) => (
                  <div key={label} className="bg-ivory-100 rounded-lg p-2 text-center">
                    <p className="text-[10px] font-bold text-charcoal-500 uppercase">{label}</p>
                    <p className="font-extrabold text-forest-900 mt-0.5">{value || '—'}</p>
                  </div>
                ))}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};
